### ISSUE TITLE
Some missing AI journals

### ISSUE THREAD

**Issue by dananau** [csmetrics/csmetrics.org#12]
I'm pretty surprised to see that your list of Artificial intelligence journals omits the two main journals for AI:
 - Artificial Intelligence
 <https://www.journals.elsevier.com/artificial-intelligence>
 - Journal of Artificial Intelligence Research 
<https://www.jair.org/index.php/jair>

Here are a few others that might also be worth including. Although they aren't as good as the above two, they're comparable in stature to several of the other journals included in your metrics:
 - AI Magazine 
<http://www.aaai.org/Magazine/magazine.php>
 - ACM Transactions on Intelligent Systems 
<https://tist.acm.org>
 - Annals of Mathematics and Artificial Intelligence 
<https://www.springer.com/computer/ai/journal/10472>

**Comment by shinminjeong** [comment]
@dananau  Thank you for the suggestion. We have included these 5 journals in the new version.
