### ISSUE TITLE
add ICMR as the replacement conf for CIVR

### ISSUE THREAD

**Issue by lexingxie** [csmetrics/csmetrics.org#19]
ACM CIVR conference was replaced / renamed to ICMR after ~2011
https://dblp.org/db/conf/mir/index.html

**Comment by shinminjeong** [comment]
ICMR added (2011~) [faf777e737b6078f0907be5c03b820f278f84dfa](https://github.com/csmetrics/csmetrics.org/commit/faf777e737b6078f0907be5c03b820f278f84dfa)
