### ISSUE TITLE
show default ranking on load

### ISSUE THREAD

**Issue by lexingxie** [csmetrics/csmetrics.org#3]
from Alan Mislove, to fix after the site is up
 "
- IIRC, I had to click “Rank” before anything happened, meaning I was staring at the site for a minute or so before I realized it was waiting on me before showing any results.  I’d have it written so that, on load, it loads the default rankings settings and shows something
"

**Comment by xuqiongkai** [comment]
Fixed: (commit 1f1841040d31ca5902bd38cb184a826a5769a1a2)
Add dorank func to onload process of main page. Need to wait for 1 seconds. (Non-perfect, wait for further solution)

**Comment by csmetrics** [comment]
resolved after UI update.
