### ISSUE TITLE
ErrorReport:École Polytechnique Fédérale de Lausanne:type:Education

### ISSUE THREAD

**Issue by LPTK** [csmetrics/csmetrics.org#38]
AFAIK, EPFL has the same status as ETHZ. But ETHZ is classified as 'Education' while EPFL is currently classified as 'Facility'.

Also, the naming seems inconsistent: in `ETH Zurich`, `ETH` stands for `Eidgenössische Technische Hochschule`. But in the case of EPFL, it is spelled out completely as `École Polytechnique Fédérale de Lausanne`. What's the policy on acronyms?

**Comment by shinminjeong** [comment]
@LPTK Thanks for your report! I have fixed the EPFL as 'Education'.

About classification and acronyms of the institutions, we currently follow [Microsoft academic](https://academic.microsoft.com/)'s policy. Visit their [FAQ](https://academic.microsoft.com/faq) for more information.
