### ISSUE TITLE
"CS Education" Category?

### ISSUE THREAD

**Issue by acbart** [csmetrics/csmetrics.org#4]
Would there be any possibility for a "CS Education" Category? This could represent SIGCSE, ITiCSE, ICER, L@S, etc. I previously made this request to the [csrankings](https://github.com/emeryberger/CSrankings/issues/11) group, but they did not feel that the area met their requirements. That means there's a big gap in the "rankings market" for a tool that can help CS Ed researchers!

**Comment by mapq** [comment]
Agreed. Also missing ACM TOCE.

**Comment by lexingxie** [comment]
we'll take this into account in the next version of csmetrics (under planning), stay tuned.

**Comment by shinminjeong** [comment]
@acbart @mapq Thank you for the suggestion.
SIGCSE, ITiCSE, ICER, L@S and TOCE are now included under CS Education Category.

**Comment by acbart** [comment]
Thank you for including this data! It's really fascinating to see how it turns out. Glancing over the names, it seems like the results are more or less what I'd expect. Cool tool!
