### ISSUE TITLE
Add AISTATS

### ISSUE THREAD

**Issue by wpzdm** [csmetrics/csmetrics.org#40]
AISTATS: https://aistats.org/

I think, and many will agree, its overall influence in the machine learning and AI field is comparable to AAAI and UAI.
And if we consider theoretical papers, AISTATS is stronger than both others.

Also, I think, if we should choose only one category, AISTATS is better fit into "machine learning", rather than "AI", despite what its name would suggest.

**Comment by shinminjeong** [comment]
AISTATS is added in 2021 update.
See the new venue list: https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv
