### ISSUE TITLE
Add ICLR?

### ISSUE THREAD

**Issue by wpzdm** [csmetrics/csmetrics.org#41]
ICLR: iclr.cc

I am a bit confused, but I cannot find ICLR under AI or machine learning.
It is _the_ conference in deep learning, and its H5 index on google is even higher than Neurips now.

I will say Neurips, ICML, and ICLR are the three best conferences in machine learning.

**Comment by shinminjeong** [comment]
ICLR is added in 2021 update.
See the new venue list: https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv
