### ISSUE TITLE
PAMI should also belong to "Vision"

### ISSUE THREAD

**Issue by wpzdm** [csmetrics/csmetrics.org#42]
The name is "Pattern Analysis & Machine Intelligence".
While it contains "Machine Intelligence", the focus is vison. 
"Pattern Analysis" basically means computer vision (We also have "International Conference on Pattern Recognition", which is a vision conference).

**Comment by shinminjeong** [comment]
This is fixed with the 2021 update!
See the new venue list: https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv
