### ISSUE TITLE
DAC is expanded incorrectly

### ISSUE THREAD

**Issue by sampsyo** [csmetrics/csmetrics.org#5]
DAC under the architecture category is listed as "Digital Arts and Culture":

<img width="579" alt="screenshot 2017-09-15 14 35 49" src="https://user-images.githubusercontent.com/188033/30498097-6cc0360a-9a23-11e7-96e4-19aa60b3c4fa.png">

which I'm sure is a fine conference in its own right, but the architecture-relevant one is the [Design Automation Conference](https://dac.com).

**Comment by kathryn1mckinley** [comment]
We should have two conferences:

ARTECH: Digital Arts and Culture (which used to go by DAC and now goes by ARTECH)
DAC: Design Automation Conference

Which one do we currently have?  We should add the one we are missing.  

Kathryn

**Comment by kathryn1mckinley** [comment]
Because it seems pretty clear we currently have Digital Arts and Culture, I just fixed the categories for it.

**Comment by shinminjeong** [comment]
Close the issue. [commit d9679b052653ddf0f58865826a89a3a64f25d586](https://github.com/csmetrics/csmetrics.org/commit/d9679b052653ddf0f58865826a89a3a64f25d586
)
