### ISSUE TITLE
where is the 'go' button ???

### ISSUE THREAD

**Issue by pratt3000** [csmetrics/csmetrics.org#50]

**Comment by shinminjeong** [comment]
Hi @pratt3000 
Thank you for reporting this! 
We removed the "Go" button since the last update but it seems we forgot to update the message on the table. 
The ranking will be automatically updated when you change the configurations.

**Comment by shinminjeong** [comment]
Fixed with the commit [cebbc9aa61920187264e4f32258f7790bc258a4e](https://github.com/csmetrics/csmetrics.org/commit/cebbc9aa61920187264e4f32258f7790bc258a4e#diff-a172cedcae47474b615c54d510a5d84a8dea3032e958587430b413538be3f333)
