### ISSUE TITLE
Request to add TMI and rename TITB to JBHI

### ISSUE THREAD

**Issue by mayurmallya** [csmetrics/csmetrics.org#51]
Thanks for this wonderful project! 

I could find MICCAI and IPMI conferences that are relevant to Medical Imaging. If you could add IEEE [TMI](https://www.embs.org/tmi/) that would be great.

Secondly, I see that there is IEEE TITB in the venue list. It has been renamed to IEEE JBHI ([link](https://www.embs.org/jbhi/about-j-bhi/)). Please rename it in your venue list too.

Thank you.

**Comment by shinminjeong** [comment]
Hi @mayurmallya 
Thank you for sharing the information. IEEE TITB is now renamed to IEEE JBHI.
We will consider adding IEEE TMI in the next update!

**Comment by shinminjeong** [comment]
IEEE TMI is added in 2022 update.
See the new venue list: https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv
