### ISSUE TITLE
Feature Request: Shareable links

### ISSUE THREAD

**Issue by vikasnataraja** [csmetrics/csmetrics.org#54]
It would be brilliant to have shareable links so one can share any changes they have made within the tool. For example, I am currently looking at only 5 topics/categories and have custom \alpha value and selected the conferences that I am interested in. But, I can't save that link or share that with anyone. I know CSRankings.org just uses dynamic links so any time something changes within the tool, the url changes. Or just a share option would help.

**Comment by shinminjeong** [comment]
Hi @vikasnataraja 
We implemented the shareable link option and you can now find the "Copy Sharable Link" button on the top right corner. Thank you for the wonderful suggestion! 👍 

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/8980616/161497653-c3730028-f86d-44b4-b669-f593e2a709f9.png">
