### ISSUE TITLE
ErrorReport:University of Science and Technology of China:type:Education

### ISSUE THREAD

**Issue by Mingkai-Li** [csmetrics/csmetrics.org#55]
I hope to report an error in this exciting project. *University of Sciecne and Technology of China (USTC)* is a **public university**. However, it's listed as a government organization in csmetrics. It's under the leadrship of *Chinese Academy of Science*, but it's not a part of it, it runs independently (similar to ShanghaiTech University). Detailed information can be find in [wikipedia](https://en.wikipedia.org/wiki/University_of_Science_and_Technology_of_China) and [school website](http://en.ustc.edu.cn/About.htm).

Thank you.

**Comment by shinminjeong** [comment]
Hi @Mingkai-Li 
Thank you for reporting this! this is fixed now.
