### ISSUE TITLE
Update for 2022

### ISSUE THREAD

**Issue by SethPoulsen** [csmetrics/csmetrics.org#59]
Currently the website seems to only be showing publications up to 2019. How can we get this updated for more recent years?

**Comment by shinminjeong** [comment]
Hi @SethPoulsen 
The current website includes the publications up to 2020 (updated on Jun 2021). You can also check the update summary here: https://github.com/csmetrics/csmetrics.org/blob/master/docs/2021_update_summary/2021_update_report.pdf

We are working on another update with the publication up to 2021. You will see it soon! :)
