### ISSUE TITLE
Add IEEE/ACM UCC and BDCAT conferences

### ISSUE THREAD

**Issue by alansill** [csmetrics/csmetrics.org#62]
Please add the IEEE and ACM co-sponsored conferences on Utility and Cloud Computing [(UCC)](https://ucc-conference.org) and Big Data Computing, Applications, and Technologies [(BDCAT)](https://bdcat-conference.org) that should be easy to include because their proceedings are published by the sponsoring organizations (alternating years between IEEE and ACM by mutual agreement) and should be easy to find. Here are some summary links.

- [UCC (ACM)](https://dl.acm.org/conference/ucc)
- [UCC (IEEE)](https://ieeexplore.ieee.org/xpl/conhome/1800743/all-proceedings)
- [BDCAT (ACM)](https://dl.acm.org/conference/bdcat)
- [BDCAT (IEEE)](https://ieeexplore.ieee.org/xpl/conhome/1805846/all-proceedings)

Contact the conference organizers if needed. (I am one of the general co-chairs for 2022).

**Comment by alansill** [comment]
Update: Here are the DBLP conference names and links for these two conferences:

[UCC](https://dblp.org/streams/conf/ucc)
[BDCAT](https://dblp.org/streams/conf/bdc)

**Comment by shinminjeong** [comment]
Hi @alansill 

Thank you for your suggestion. UCC and BDCAT have been included in the 2023 update.
See the new venue list: https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv

I have categorized both UCC and BDCAT under the **systems** category. However, if you believe this categorization does not accurately represent these conferences, please let me know, and I will make the necessary adjustments.
