### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by DeqingFu** [csmetrics/csmetrics.org#65]
Got the following:

csmetrics.org has expired and is parked free, courtesy of GoDaddy.com.

**Comment by emeryberger** [comment]
@lexingxie @steveblackburn looks like this is the issue. Someone may have taken over the domain :(.

**Comment by steveblackburn** [comment]
:(.  Thanks Emery

**Comment by adityamwagh** [comment]
Is there some other URL like `csmetrics.github.io` to access the website?

**Comment by emeryberger** [comment]
https://csmetrics.net/ now works.

**Comment by adityamwagh** [comment]
Great! So does this mean someone just pirated the `csmetrics.org` and is holding it ransom, so the maintainers are not going to do anything about it?

**Comment by shinminjeong** [comment]
@DeqingFu @adityamwagh Thank you for reporting this and sorry for your inconvenience.
Many thanks to @emeryberger for letting us know.

We, unfortunately, lost our domain and had to transfer it to [csmetrics.net](https://csmetrics.net/ ).  
The new website using csmetrics.org seems to be a legitimate site. It is entirely our fault for not paying attention to domain name expiry date.

@adityamwagh `csmetrics.github.io` is also a good alternative. We should make it available too.
