### ISSUE TITLE
The "region" data are messed up

### ISSUE THREAD

**Issue by wpzdm** [csmetrics/csmetrics.org#67]
Many institutions are assigned to the wrong region.

**Comment by shinminjeong** [comment]
Thanks, @wpzdm, for bringing this to our attention!

We believe this issue arose after transitioning our data source from Microsoft Academic Graph to OpenAlex.

We're actively investigating the matter and will update the affected regions with the correct information. In the meantime, we encourage you to report any inaccuracies you encounter by clicking them.
