### ISSUE TITLE
Add Core-A SE venues, especially ICSA

### ISSUE THREAD

**Issue by AnneKoziolek** [csmetrics/csmetrics.org#68]
I see that there a few SE venues that are ranked A in the CORE ranking, but not all of them. In particular I am missing IEEE ICSA, which is the premier conference on software architecture. 

I suggest to add all CORE-A SE venues. Here is the list: http://portal.core.edu.au/conf-ranks/?search=Software&by=all&source=CORE2023&sort=arank&page=1

Here is the DBLP link for ICSA: https://dblp.org/db/conf/icsa/index.html

Thanks!

**Comment by shinminjeong** [comment]
Hi @AnneKoziolek 
Thanks for your suggestion. ICSA has been added in the 2024 update! 
See [https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv](https://github.com/csmetrics/csmetrics.org/blob/master/app/data/venue_list.csv)

Adding other Core-A venues is also a valuable suggestion; however, this could lead to including all Core-A venues from other fields as well. We will discuss it internally and consider incorporating it in the next update.

**Comment by AnneKoziolek** [comment]
Thank you! 🙏
