### ISSUE TITLE
Feature: filter by country

### ISSUE THREAD

**Issue by osalbahr** [csmetrics/csmetrics.org#69]
Rationale: to help with finding the top institutions compared to others in the same country/region (similarly to https://csrankings.org)

**Comment by csmetrics** [comment]
Hi @osalbahr 

Thank you for your interest in csmetrics.net! 
Currently, the country filter is available in the right panel, allowing you to select a country to compare top institutions. 

In the snapshot, Australia is selected as an example. Feel free to choose any country to view the corresponding institutions.
<img width="774" alt="image" src="https://github.com/user-attachments/assets/0ef7d048-ca40-4449-bb08-5c3da10184d4">

**Comment by osalbahr** [comment]
Thx! Yeah, I forgot I opened this issue.
