### ISSUE TITLE
website link

### ISSUE THREAD

**Issue by zxchen-88** [csmetrics/csmetrics.org#70]
The "CS metrics team" link on the page led to a weird Japanese website (csmetrics.org) where there is something about CSMetrics and other random content. I know that csmetrics.org has been taken but please change all usages and appearances of "csmetrics.org" to "csmetrics.net" so that we will not be led to the wrong website which can be malicious.

**Comment by zxchen-88** [comment]
@shinminjeong In case you do not check the issues frequently

**Comment by shinminjeong** [comment]
Hi @zxchen-88
Thank you for letting me know! I will update it quickly :)
