### ISSUE TITLE
Non applicable country

### ISSUE THREAD

**Issue by StEvUgnIn** [csmetrics/csmetrics.org#77]
Bouvet is a dependent territory of Norway, but remains uninhabited.

https://github.com/csmetrics/csmetrics.net/blob/e7806bf9f74eb348e6aca792598a3448ebf146d1/app/data/country_code.csv#L31

Please remove this entry from [country_code.csv](csmetrics/csmetrics.net/tree/master/app/data/country_code.csv)

**Comment by StEvUgnIn** [comment]
@shinminjeong Do you think this country is important to the dataset since it is currently uninhabited, and might be unhabitable due to its natural climate?

**Comment by shinminjeong** [comment]
Thank you for the helpful information!
The country_code.csv file is used to obtain continent information for institutions, so if there is no institution associated with Bouvet, it won't be used. Therefore, there’s no need to remove the country code :)
